### ISSUE TITLE
预训练模型下载下来的文件名和代码中的文件名不同，只需要重命名就可以吗？

### ISSUE THREAD

**Issue by SuperCarryFu** [qilong-zhang/Targeted_Patch-wise-plusplus_iterative_attack#1]

**Comment by qilong-zhang** [comment]
@SuperCarryFu 应该是一样的吧？你说哪个模型名字不一样

**Comment by SuperCarryFu** [comment]
您论文中的代码
    'adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'adv_inception_v3_rename.ckpt'),
    'ens3_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens3_adv_inception_v3_rename.ckpt'),
    'ens4_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens4_adv_inception_v3_rename.ckpt'),
但是下载下来的预训练模型，并没有_rename

**Comment by qilong-zhang** [comment]
> 您论文中的代码 'adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'adv_inception_v3_rename.ckpt'), 'ens3_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens3_adv_inception_v3_rename.ckpt'), 'ens4_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens4_adv_inception_v3_rename.ckpt'), 但是下载下来的预训练模型，并没有_rename

你试试把代码里面的rename后缀删了，可能是我这边代码没同步

**Comment by SuperCarryFu** [comment]
好的，希望您可以尽快同步代码，再次感谢百忙之中回复我的问题。



---原始邮件---
发件人: "Qilong ***@***.***&gt;
发送时间: 2022年3月13日(周日) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qilong-zhang/Targeted_Patch-wise-plusplus_iterative_attack] 预训练模型下载下来的文件名和代码中的文件名不同，只需要重命名就可以吗？ (Issue #1)




  
您论文中的代码 'adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'adv_inception_v3_rename.ckpt'), 'ens3_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens3_adv_inception_v3_rename.ckpt'), 'ens4_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens4_adv_inception_v3_rename.ckpt'), 但是下载下来的预训练模型，并没有_rename
  
你试试把代码里面的rename后缀删了，可能是我这边代码没同步
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qilong-zhang** [comment]
> 好的，希望您可以尽快同步代码，再次感谢百忙之中回复我的问题。
> […](#)
> ---原始邮件--- 发件人: "Qilong ***@***.***&gt; 发送时间: 2022年3月13日(周日) 下午4:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qilong-zhang/Targeted_Patch-wise-plusplus_iterative_attack] 预训练模型下载下来的文件名和代码中的文件名不同，只需要重命名就可以吗？ (Issue #1) 您论文中的代码 'adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'adv_inception_v3_rename.ckpt'), 'ens3_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens3_adv_inception_v3_rename.ckpt'), 'ens4_adv_inception_v3': os.path.join(FLAGS.checkpoint_path, 'ens4_adv_inception_v3_rename.ckpt'), 但是下载下来的预训练模型，并没有_rename 你试试把代码里面的rename后缀删了，可能是我这边代码没同步 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

已经改好了 你看看现在对不对

**Comment by SuperCarryFu** [comment]
谢谢！

**Comment by SuperCarryFu** [comment]
您的另一个仓库也同样具有这个问题[Patch-wise-iterative-attack](https://github.com/qilong-zhang/Patch-wise-iterative-attack)

**Comment by qilong-zhang** [comment]
> 您的另一个仓库也同样具有这个问题[Patch-wise-iterative-attack](https://github.com/qilong-zhang/Patch-wise-iterative-attack)

已修正，感谢提醒。

**Comment by SuperCarryFu** [comment]
不客气
