### ISSUE TITLE
n_staircase_sign这个函数为定义

### ISSUE THREAD

**Issue by SuperCarryFu** [qilong-zhang/Targeted_Patch-wise-plusplus_iterative_attack#2]
n_staircase_sign这个函数未定义。DTPI-FGSM++_for_NT.py的第127行，同时fdnets无法导入，它似乎在net文件夹下，同时third-party不存在

**Comment by qilong-zhang** [comment]
你是不是弄错了，这个函数应该是在这个仓库https://github.com/qilong-zhang/Staircase-sign-method。

**Comment by SuperCarryFu** [comment]
amplification += alpha_beta * n_staircase_sign(noise, num_of_K)
这是使用这个函数的代码，他在DTPI-FGSM++_for_NT.py文件中

**Comment by qilong-zhang** [comment]
谢谢提醒，我之前太仓促了 没仔细检查。现在修改好了。

**Comment by SuperCarryFu** [comment]
如果可以的话，您可以重新整理上传一下吗？因为还有一些包括我提出的fdnets和third_party模块找不到，不能导入的情况。

**Comment by qilong-zhang** [comment]
fdnets我已经注释掉了了，third_party是在哪？ 那个也可以注释掉

**Comment by SuperCarryFu** [comment]
在nets/adv_model.py的第18行

**Comment by SuperCarryFu** [comment]
但是他似乎被调用了

**Comment by qilong-zhang** [comment]
你可以不用管他，这个与论文中的那些模型没关系，攻击相关的代码在执行中也不会有调用。

**Comment by SuperCarryFu** [comment]
谢谢，问题已经解决了
